# Generated by Django 4.0.4 on 2022-04-26 13:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_image_product_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='product_images'),
        ),
    ]
