# Generated by Django 4.0.4 on 2022-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='post_image',
            new_name='image',
        ),
    ]
